language: cpp

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCATERPILLAR_TEST=ON -DCATERPILLAR_EXAMPLES=ON ..
  - make 

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    addons:
      apt:
        sources: 
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env: COMPILER=g++-7
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env: COMPILER=g++-8
  - os: linux
    dist: trusty
    sudo: required
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0
        packages:
          - clang-6.0
          - g++-7
    env: COMPILER=clang++-6.0
  - os: osx
    osx_image: xcode10.3
    compiler: clang
    before_install:
      - brew update
      - brew install llvm
    env: COMPILER=/usr/local/opt/llvm/bin/clang++
  - os: osx
    osx_image: xcode10.3
    compiler: gcc
    before_install:
      - export HOMEBREW_NO_INSTALL_CLEANUP=1
      - brew uninstall --ignore-dependencies gcc
      - brew update
      - brew install gcc
    env: COMPILER=/usr/local/opt/gcc/bin/g++-9
  - os: osx
    osx_image: xcode10.3
    compiler: gcc
    before_install:
      - brew update
      - brew install gcc@8
    env: COMPILER=/usr/local/opt/gcc@8/bin/g++-8
